// Generated by CoffeeScript 1.10.0
(function() {
  var TYPESAFE_FAIL, error, error1, foo, mydata, typesafe;

  typesafe = require('../index.coffee').typesafe;

  mydata = {
    type: "object",
    properties: {
      foo: {
        type: "string",
        regex: /abc/
      },
      bar: {
        type: "integer",
        minimum: 0,
        maximum: 100
      },
      records: {
        type: "array",
        items: [
          {
            name: {
              type: "string",
              minLength: 2
            },
            age: {
              type: "integer"
            }
          }
        ]
      }
    },
    required: ["foo", "records"]
  };

  foo = typesafe(mydata, function(data) {
    return console.log("valid data passed!");
  });

  try {
    foo({});
  } catch (error) {
    TYPESAFE_FAIL = error;
    console.log("ok");
  }

  foo = typesafe({
    foo: {
      type: "string"
    },
    bar: {
      type: "integer"
    }
  }, function(foo, bar) {
    return console.log("arguments are valid");
  });

  try {
    foo(123, 123);
  } catch (error1) {
    TYPESAFE_FAIL = error1;
    console.log("recover");
  } finally {
    console.log("finish");
  }

}).call(this);
