// Generated by CoffeeScript 1.10.0
(function() {
  var clone, tjv;

  tjv = require('tiny-json-validator');

  clone = function(o) {
    return JSON.parse(JSON.stringify(o));
  };

  module.exports = (function() {
    var typeshave;
    typeshave = this;
    this.verbose = 0;
    this.onError = (function(_this) {
      return function(err) {
        if (_this.verbose > 0) {
          console.dir({
            'typeshave exception': err
          });
        }
        throw "TYPESAFE_FAIL";
      };
    })(this);
    this.typesafe = function(schema, method) {
      var validated;
      validated = function() {
        var args, dump, k, v;
        if (schema.type == null) {
          args = {};
          for (k in schema) {
            v = schema[k];
            args[k] = arguments[k];
          }
          console.dir({
            "simple args": args
          });
          v = tjv({
            type: "object",
            required: Object.keys(schema),
            properties: schema
          }, args);
        } else {
          console.dir({
            "phat obj": arguments
          });
          v = tjv(schema, arguments[0]);
          console.dir(arguments[0]);
        }
        if (!v.isValid) {
          dump = {
            data: arguments,
            errors: v.errors,
            schema: schema
          };
          typeshave.onError(dump);
        }
        return method.apply(this, arguments);
      };
      return validated;
    };
    return this;
  })();

}).call(this);
