// Generated by CoffeeScript 1.10.0
(function() {
  var tv4;

  tv4 = require('tv4');

  module.exports = (function() {
    this.onError = function(err) {
      var e, j, len, ref;
      ref = err.errors;
      for (j = 0, len = ref.length; j < len; j++) {
        e = ref[j];
        console.log("typesafe error: " + String(e.dataPath).replace(/\//g, '.') + " " + e.message);
      }
      throw "TYPESAFE_FAIL";
    };
    this.typesafe = function(schema, method) {
      var me, typeshave, validated;
      typeshave = me = this;
      validated = function() {
        var args, dump, i, k, v;
        if (schema.type == null) {
          args = {};
          i = 0;
          for (k in schema) {
            v = schema[k];
            args[k] = arguments[String(i++)];
          }
          schema = {
            type: "object",
            required: Object.keys(schema),
            properties: schema
          };
          arguments[0] = args;
        }
        v = tv4.validateMultiple(arguments[0], schema);
        if (!v.valid) {
          dump = {
            data: arguments[0],
            errors: v.errors,
            schema: schema
          };
          if (process.env.DEBUG) {
            console.log(JSON.stringify(dump, null, 2));
          }
          typeshave.onError(dump);
        }
        return method.apply(this, arguments);
      };
      return validated;
    };
    return this;
  })();

}).call(this);
