#!/bin/bash
      find . -name "*.coffee" | grep -v node_modules | while read file; do 
        echo "compiling ${file/coffee$/js/g}"; 
        coffee -c -b --no-header "$file"; git add "${file/coffee$/js/}"; 
      done
